version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_seeker_polytron
    volumes:
      - .:/var/www/html
    ports:
      - "8004:80"
    depends_on:
      - job_seeker_polytron

  job_seeker_polytron:
    image: mysql:8.0
    container_name: mysql_db_job_seeker_polytron
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_job_seeker_polytron
    volumes:
      - db_data_job_seeker_polytron:/var/lib/mysql
      - ./db_job_seeker_polytron.sql:/docker-entrypoint-initdb.d/database.sql:ro
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_job_seeker_polytron
    depends_on:
      - job_seeker_polytron
    ports:
      - "9004:80"
    environment:
      PMA_HOST: job_seeker_polytron
      MYSQL_ROOT_PASSWORD: root
    restart: always

volumes:
  db_data_job_seeker_polytron:
